[package]
name = "iroh-chain"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "iroh network layer for chains of keys"

[lib]
name = "iroh_chain"

[features]
default = []
utoipa = ["dep:utoipa"]
axum = ["dep:axum"]


[dependencies]
# Iroh
iroh = { version = "1.1",  default-features = false, features = [] }


# Web
utoipa = { version = "5.5", default-features = false, features = [
  "macros",
  "chrono",
], optional = true }
axum = { version = "0.8", default-features = false, features = [
  "json",
], optional = true }

# Serialization
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }

# Utilities
blake3 = { version = "1.8", default-features = false, features = [] }


# Async

tokio = { version = "1.53", default-features = false, features = [
  "io-util",
  "macros",
  "rt",
  "sync",
  "time",
] }

noq = { version = "1.2", default-features = false, features = [] }


[dev-dependencies]
iroh = { version = "1.1",  default-features = true }

log = "0.4"
env_logger = "0.11"
test-log = "0.2"
